Feature/11153 service instance id on non bulk orders
nhs-digital-gp-it-futures/order-form pull request #405
Opened 2021-01-14 12:45 UTC by bjss-andrew

copied over the instance id for none bulk orders from develop branch to be merged into master

2021-01-14 12:53 UTC, PhysicsJon requested changes
Just a couple of missing EoF newlines, will need a more in depth review to ensure the correct changes have been made

2021-01-14 12:53 UTC, PhysicsJon commented on app/pages/summary/template.njk
> +{% endblock %}
EoF newline?

2021-01-14 12:53 UTC, PhysicsJon commented on example.env
> +REDIS_PASS=
EoF newline?

2021-01-14 12:59 UTC, bjss-andrew commented on app/pages/summary/template.njk
> +{% endblock %}
done

2021-01-14 12:59 UTC, bjss-andrew commented on example.env
> +REDIS_PASS=
done

2021-01-14 13:00 UTC, bjss-andrew commented
added rule to eslint for a new line at the end
need to put in something to link template files too

2021-01-15 10:25 UTC, bjss-chris approved these changes

2021-01-15 10:31 UTC, PhysicsJon approved these changes

2021-01-15 10:33 UTC, merged