multi build docker - 600 ish mb
nhs-digital-gp-it-futures/order-form pull request #445
Opened 2021-02-15 12:33 UTC by bjss-andrew

2021-02-15 13:52 UTC, bjss-chris requested changes

2021-02-15 13:52 UTC, bjss-chris commented on Dockerfile
Not sure we need all these blank lines! 😃

2021-02-16 09:26 UTC, PhysicsJon approved these changes

2021-02-16 09:32 UTC, bjss-chris requested changes

2021-02-16 09:32 UTC, bjss-chris commented on Dockerfile
> +# RUN find ./ -mindepth 1 ! -regex '^./dist\(/.*\)?' -delete
Is the plan to reinstate these commented-out lines at some point?

2021-02-16 09:32 UTC, bjss-chris commented on Dockerfile
> +
Sorry, missed this extra blank line last time! One should be sufficient 😃

2021-02-16 11:45 UTC, bjss-chris approved these changes

2021-02-18 11:12 UTC, merged